### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spectrum-generator#10]
A peak may either be an array of 2 elements or an object with {x,y} properties.

Please could you help me to write correctly the ts definition ?

So addPeaks could either be array of array (2 elements) or array of object (x,y, properties).

Add addPeak can either be an array of 2 elements or an object containing x,y properties.

https://github.com/cheminfo/spectrum-generator/blob/cfb3441f75f846faaf4e51d9a32b582b94c849c1/spectrum-generator.d.ts#L126-L137

**Comment by targos** [comment]
You want to allow two different types in a parameter? You can create an union with the `|` operator:

```ts
interface XYObject {
  x: number;
  y: number;
}

class SG {
  // ...

  addPeaks(peaks: number[][] | XYObject[]): this;

  addPeak(peak: number[] | XYObject, options?: PeakOptions): this;

  // ...
}
```

**Comment by targos** [comment]
Alternative:

```ts
interface XYObject {
  x: number;
  y: number;
}

type Peak = [number, number] | XYObject;

class SG {
  // ...

  addPeaks(peaks: Peak[]): this;

  addPeak(peak: Peak, options?: PeakOptions): this;

  // ...
}
```
