### ISSUE TITLE
addPeak function edit the internal properties

### ISSUE THREAD

**Issue by jobo322** [cheminfo/spectrum-generator#67]
```js
const peaks = [
  { x: -0.5, y: -2, width: 0.12, shape: { kind: 'pseudoVoigt' as const, mu: 0.1 } },
  { x: 0, y: 1, width: 0.12},
];

const data = generateSpectrum(peaks, {
  generator: {
    from,
    to,
    nbPoints: 256,
    shape: {
      kind: 'gaussian',
    },
  },
});
```

you will obtain 2 pseudovoigt shapes with `mu` equal 0.1, even if `shape` is defined in the options.

@lpatiny should addPeak be a `pure method`, I mean, should it not make a permanent changes on internal parameters?

**Comment by lpatiny** [comment]
It should be a pure function so peaks should not be changed. If it is not the case this is a bug.

Concerning your example if shape is defined at the level of the peak it is priority. So the first peak should be a pseudovoigt and the second peak that was not defined should be a gaussian.
